# Generated by Django 4.2.15 on 2025-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('date_access', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('final_level_1_consensus', models.CharField(blank=True, max_length=255)),
                ('exclusion_reason_final_level_1', models.TextField(blank=True)),
                ('final_level_2_consensus', models.CharField(blank=True, max_length=255)),
                ('exclusion_reason_final_level_2', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('research_paper_type', models.CharField(blank=True, max_length=255)),
                ('country_organisation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
