# Generated by Django 4.2.15 on 2025-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('date_access', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('final_level_1_consensus', models.CharField(blank=True, max_length=255)),
                ('exclusion_reason_final_level_1', models.TextField(blank=True)),
                ('final_level_2_consensus', models.CharField(blank=True, max_length=255)),
                ('exclusion_reason_final_level_2', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('research_paper_type', models.CharField(blank=True, max_length=255)),
                ('country_organisation', models.CharField(blank=True, max_length=255)),
                ('abstract', models.TextField(blank=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
